### PR TITLE
Add TLX Training Gate

### PR DESCRIPTION
**Pull request by turfaa**
Add TLX Training Gate Berbahasa Indonesia repository. Good for learning competitive programming.

### CODE REVIEW

**Comment by jayvdb** [comment]
:+1:

p.s. s/Traning/Training/ in the commit message, if you want to amend it.
Only very minor; not very important ;-)

**Comment by jayvdb** [comment]
merge conflicts to resolve.
Your opportunity to practise your advanced git skills.

**Comment by turfaa** [comment]
@jayvdb  done :+1:

**Comment by jayvdb** [comment]
@turfaa , try to `git rebase` and `git squash` so your PR is only one clean commit.

**Comment by zhiephie** [comment]
Please fix your conflict!

**Pull request closed without merging**
